# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=200)),
                ('result_1', models.IntegerField(null=True)),
                ('result_2', models.IntegerField(null=True)),
                ('result_3', models.IntegerField(null=True)),
                ('result_4', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cox',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_cox', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crew',
            name='bow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bow', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasybumps.Club'),
        ),
        migrations.AddField(
            model_name='crew',
            name='cox',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cox', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='five',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='four',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='seven',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='six',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='stroke',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stroke', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='three',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='crew',
            name='two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='fantasybumps.Rower'),
        ),
    ]
