# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='year',
            field=models.IntegerField(default=2016),
        ),
        migrations.AddField(
            model_name='profile',
            name='stroke',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_stroke', to='fantasybumps.Rower'),
        ),
    ]
