# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybumps', '0002_auto_20170419_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='result_1',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
