# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasybumps', '0003_auto_20170419_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='year',
        ),
        migrations.AddField(
            model_name='profile',
            name='bow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_bow', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='five',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_five', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='four',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_four', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seven',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_seven', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='six',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_six', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='three',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_three', to='fantasybumps.Rower'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_two', to='fantasybumps.Rower'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='result_1',
            field=models.IntegerField(null=True),
        ),
    ]
